name: .NET Debezium CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: Setup .NET 8
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: 8.0.x

          - name: Restore dependencies
            run: dotnet restore src/DebeziumPostgresRabbitmqConsumer

          - name: Build
            run: dotnet build src/DebeziumPostgresRabbitmqConsumer --no-restore